name: Data Structure Check

on:
  push:
    branches:
      - '*'
    # Exclude the main branch
    # `!main` excludes the main branch
    # This means it will run on all branches except `main`
    # (the `*` wildcard includes all branches)
    branches-ignore:
      - 'main'

jobs:
  test_data_structure:
    runs-on: ubuntu-latest  # You can change this to another OS if you prefer

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # This action checks out the code from the repository

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'  # Set the desired Python version (use '3.x' for latest)

    - name: Run data structure test
      run: |
        python scripts/data_structure_test.py  # Run your Python script that checks the data structure
