name: Data Structure Check

on:
  push:
    branches-ignore:
      - 'main'

jobs:
  test_data_structure:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # This action checks out the code from the repository

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Check if data directory exists
      run: |
        if [ ! -d "./data" ]; then
          echo "No data found. Skipping test."
          exit 0
        fi

    - name: Run data structure test
      run: |
        python data_structure_test.py  
